bigquery:
  region: US
  key:
    file: bigquery_key.json

anthropic:
  model: claude-3-sonnet-20240229
  # model: claude-3-haiku-20240307
  # model: claude-3-opus-20240229
  key:
    file: anthropic_key.txt